export const MOCK_DOCTORS = [
  {
    id: 'dr1',
    name: 'د. أحمد محمد حسن',
    nameEn: 'Dr. Ahmed Mohamed Hassan',
    specialty: 'باطنة و gastro',
    specialtyEn: 'Internal Medicine',
    experience: 14,
    rating: 4.9,
    reviews: 218,
    consultPrice: 150,
    available: true,
    nextSlot: 'اليوم 4:30 م',
    nextSlotEn: 'Today 4:30 PM',
    bio: 'استشاري أمراض باطنة — متخصص في السكر، الضغط، وأمراض الجهاز الهضمي.',
    bioEn: 'Internal medicine consultant — diabetes, hypertension, and GI disorders.',
    conditions: ['سكر', 'ضغط', 'قرحة', 'حموضة'],
    conditionsEn: ['Diabetes', 'Hypertension', 'Ulcers', 'Acid reflux'],
    avatar: null,
    verified: true,
  },
  {
    id: 'dr2',
    name: 'د. سارة علي إبراهيم',
    nameEn: 'Dr. Sara Ali Ibrahim',
    specialty: 'أطفال وحديثي الولادة',
    specialtyEn: 'Pediatrics',
    experience: 10,
    rating: 4.95,
    reviews: 312,
    consultPrice: 120,
    available: true,
    nextSlot: 'غداً 10:00 ص',
    nextSlotEn: 'Tomorrow 10:00 AM',
    bio: 'طبيبة أطفال — متابعة النمو، التطعيمات، وعلاج نزلات البرد والحساسية.',
    bioEn: 'Pediatrician — growth follow-up, vaccinations, colds and allergies.',
    conditions: ['حمى', 'سعال', 'حساسية', 'تطعيمات'],
    conditionsEn: ['Fever', 'Cough', 'Allergies', 'Vaccinations'],
    avatar: null,
    verified: true,
  },
  {
    id: 'dr3',
    name: 'د. محمود خالد سيد',
    nameEn: 'Dr. Mahmoud Khaled Said',
    specialty: 'جلدية وتجميل طبي',
    specialtyEn: 'Dermatology',
    experience: 8,
    rating: 4.8,
    reviews: 156,
    consultPrice: 180,
    available: false,
    nextSlot: 'الأحد 2:00 م',
    nextSlotEn: 'Sunday 2:00 PM',
    bio: 'أخصائي جلدية — حب الشباب، eczema، psoriasis، والعناية بالبشرة.',
    bioEn: 'Dermatologist — acne, eczema, psoriasis, and skin care.',
    conditions: ['حب الشباب', 'حساسية جلد', ' psoriasis', 'تساقط شعر'],
    conditionsEn: ['Acne', 'Skin allergy', 'Psoriasis', 'Hair loss'],
    avatar: null,
    verified: true,
  },
  {
    id: 'dr4',
    name: 'د. نورهان يوسف',
    nameEn: 'Dr. Nourhan Youssef',
    specialty: 'نساء وتوليد',
    specialtyEn: 'OB/GYN',
    experience: 12,
    rating: 4.92,
    reviews: 274,
    consultPrice: 200,
    available: true,
    nextSlot: 'اليوم 6:00 م',
    nextSlotEn: 'Today 6:00 PM',
    bio: 'استشارية نساء وتوليد — متابعة الحمل، تنظيم الأسرة، والصحة الإنجابية.',
    bioEn: 'OB/GYN consultant — pregnancy care, family planning, reproductive health.',
    conditions: ['حمل', 'دورة', ' hormonal', 'متابعة'],
    conditionsEn: ['Pregnancy', 'Menstrual', 'Hormonal', 'Follow-up'],
    avatar: null,
    verified: true,
  },
  {
    id: 'dr5',
    name: 'د. كريم عبد الرحمن',
    nameEn: 'Dr. Karim Abdel Rahman',
    specialty: 'صدرية وحساسية',
    specialtyEn: 'Pulmonology & Allergy',
    experience: 16,
    rating: 4.88,
    reviews: 189,
    consultPrice: 170,
    available: true,
    nextSlot: 'اليوم 8:00 م',
    nextSlotEn: 'Today 8:00 PM',
    bio: 'استشاري أمراض صدرية — الربو، COPD، الحساسية الموسمية، والتهاب الشعب.',
    bioEn: 'Pulmonologist — asthma, COPD, seasonal allergies, bronchitis.',
    conditions: ['ربو', 'كحة', 'حساسية', 'ضيق نفس'],
    conditionsEn: ['Asthma', 'Cough', 'Allergy', 'Shortness of breath'],
    avatar: null,
    verified: true,
  },
  {
    id: 'dr6',
    name: 'د. هبة محمد فتحي',
    nameEn: 'Dr. Heba Mohamed Fathy',
    specialty: 'طب نفسي',
    specialtyEn: 'Psychiatry',
    experience: 9,
    rating: 4.97,
    reviews: 143,
    consultPrice: 250,
    available: true,
    nextSlot: 'غداً 3:00 م',
    nextSlotEn: 'Tomorrow 3:00 PM',
    bio: 'طبيبة نفسية — القلق، الاكتئاب، insomnia، والضغط النفسي.',
    bioEn: 'Psychiatrist — anxiety, depression, insomnia, and stress.',
    conditions: ['قلق', 'اكتئاب', ' insomnia', 'ضغط نفسي'],
    conditionsEn: ['Anxiety', 'Depression', 'Insomnia', 'Stress'],
    avatar: null,
    verified: true,
  },
];

export const SPECIALTIES = ['الكل', 'باطنة', 'أطفال', 'جلدية', 'نساء', 'صدرية', 'نفسي'];

export const DOCTOR_SPECIALTY_OPTIONS = [
  { key: 'باطنة', specialty: 'طب باطنة', specialtyEn: 'Internal Medicine' },
  { key: 'أطفال', specialty: 'طب أطفال', specialtyEn: 'Pediatrics' },
  { key: 'جلدية', specialty: 'طب جلدية', specialtyEn: 'Dermatology' },
  { key: 'نساء', specialty: 'نساء وتوليد', specialtyEn: 'OB/GYN' },
  { key: 'صدرية', specialty: 'أمراض صدرية', specialtyEn: 'Pulmonology' },
  { key: 'نفسي', specialty: 'طب نفسي', specialtyEn: 'Psychiatry' },
];

export const SPECIALTY_FILTERS = {
  'الكل': () => true,
  'باطنة': (d) => d.specialty.includes('باطنة'),
  'أطفال': (d) => d.specialty.includes('أطفال'),
  'جلدية': (d) => d.specialty.includes('جلدية'),
  'نساء': (d) => d.specialty.includes('نساء'),
  'صدرية': (d) => d.specialty.includes('صدرية'),
  'نفسي': (d) => d.specialty.includes('نفسي'),
};
