import React, { useState, useEffect, useMemo } from 'react';
import { FileText, Printer, Download, Calendar, Loader2 } from 'lucide-react';
import { useSettings } from '../../context/SettingsContext';

// Firebase
import { db } from '../../firebase/config';
import { collection, onSnapshot, query, orderBy } from 'firebase/firestore';

const Reports = () => {
  const { t, lang } = useSettings(); // 👈 استدعاء اللغة والترجمة
  const [reportType, setReportType] = useState('inventory');
  const [medicines, setMedicines] = useState([]);
  const [loading, setLoading] = useState(true);

  // 1. جلب البيانات
  useEffect(() => {
    const q = query(collection(db, "medicines"), orderBy("name"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setMedicines(data);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  // 2. فلترة البيانات
  const reportData = useMemo(() => {
    if (reportType === 'shortage') {
      return medicines.filter(item => Number(item.stock) < 50);
    }
    return medicines;
  }, [reportType, medicines]);

  // الطباعة
  const handlePrint = () => {
    window.print();
  };

  // تاريخ اليوم (ديناميكي حسب اللغة)
  const today = new Date().toLocaleDateString(lang === 'ar' ? 'ar-EG' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const refNumber = Math.floor(Math.random() * 10000);

  // نصوص التقرير المتغيرة (يمكن نقلها لملف الترجمة لاحقاً)
  const reportTexts = {
    header: lang === 'ar' ? "جمهورية مصر العربية" : "Arab Republic of Egypt",
    ministry: lang === 'ar' ? "وزارة الصحة والسكان" : "Ministry of Health",
    sector: lang === 'ar' ? "قطاع التموين الطبي (ترياق)" : "Medical Supply Sector (Tiryaq)",
    title: reportType === 'inventory' 
      ? (lang === 'ar' ? 'كشف جرد المخزون' : 'Inventory Report') 
      : (lang === 'ar' ? 'تقرير النواقص الحرجة' : 'Critical Shortage Report'),
    subjectTitle: lang === 'ar' ? "الموضوع:" : "Subject:",
    subjectBody: reportType === 'inventory'
      ? (lang === 'ar' ? 'فيما يلي بيان تفصيلي بجميع الأرصدة المتاحة بالمخازن حتى تاريخه.' : 'Below is a detailed statement of all available stock in warehouses to date.')
      : (lang === 'ar' ? 'يرجى الإحاطة بوجود عجز في الأرصدة الموضحة أدناه، ونوصي بسرعة التوريد.' : 'Please note the shortage in the items listed below; urgent supply is recommended.'),
    recTitle: lang === 'ar' ? "توصيات النظام الآلي:" : "Automated Recommendations:",
    recSafe: lang === 'ar' ? "المخزون في الحدود الآمنة." : "Stock levels are safe.",
    recDanger: lang === 'ar' ? `يوجد (${reportData.filter(i => i.stock < 50).length}) أصناف تحت حد الخطر.` : `There are (${reportData.filter(i => i.stock < 50).length}) items below safety level.`,
    footerNote: lang === 'ar' ? "تم إنشاء هذا التقرير آلياً بواسطة نظام ترياق." : "Automatically generated by Tiryaq System.",
    signStore: lang === 'ar' ? "أمين المخزن" : "Store Keeper",
    signManager: lang === 'ar' ? "مدير المستشفى" : "Hospital Manager"
  };

  if (loading) return <div className="flex justify-center p-20"><Loader2 className="animate-spin text-blue-600" size={40} /></div>;

  return (
    <div className="space-y-8 animate-fade-in pb-10">
      
      {/* الهيدر (يختفي عند الطباعة) */}
      <div className="flex justify-between items-center print:hidden">
        <div>
          <h1 className="text-3xl font-bold text-gray-800 dark:text-white mb-2">
            {t.reports} 📄
          </h1>
          <p className="text-gray-500">{lang === 'ar' ? 'استخراج الوثائق الرسمية' : 'Extract Official Documents'}</p>
        </div>
        <button 
          onClick={handlePrint}
          className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-bold shadow-lg shadow-blue-500/30 transition-all flex items-center gap-2"
        >
          <Printer size={20} />
          {lang === 'ar' ? 'طباعة التقرير' : 'Print Report'}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 print:block">
        
        {/* 1. لوحة التحكم (تختفي عند الطباعة) */}
        <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-gray-100 dark:border-slate-700 shadow-sm h-fit print:hidden">
          <h3 className="font-bold text-lg text-gray-800 dark:text-white mb-4">{lang === 'ar' ? 'إعدادات التقرير' : 'Report Settings'}</h3>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">{lang === 'ar' ? 'نوع التقرير' : 'Report Type'}</label>
              <select 
                value={reportType} onChange={(e) => setReportType(e.target.value)}
                className="w-full p-2 rounded-lg bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 text-gray-800 dark:text-white outline-none"
              >
                <option value="inventory">{lang === 'ar' ? 'جرد شامل' : 'Full Inventory'}</option>
                <option value="shortage">{lang === 'ar' ? 'النواقص' : 'Shortages'}</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">{lang === 'ar' ? 'التاريخ' : 'Date'}</label>
              <div className="flex items-center gap-2 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 p-2 rounded-lg text-gray-800 dark:text-white">
                <Calendar size={18} className="text-gray-400" />
                <span>{today}</span>
              </div>
            </div>

            <div className="pt-4 border-t border-gray-100 dark:border-slate-700">
              <p className="text-xs text-gray-500 mb-2">{lang === 'ar' ? `عدد السجلات: ${reportData.length}` : `Records count: ${reportData.length}`}</p>
              <button onClick={handlePrint} className="w-full py-2 rounded-lg border border-blue-600 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors font-bold flex items-center justify-center gap-2">
                <Download size={18} />
                {lang === 'ar' ? 'تحميل PDF' : 'Download PDF'}
              </button>
            </div>
          </div>
        </div>

        {/* 2. ورقة التقرير (A4) */}
        <div className="lg:col-span-2 print:w-full print:col-span-3">
          <div className="bg-white text-black p-12 rounded-xl shadow-2xl min-h-[1123px] w-full max-w-[794px] mx-auto relative print:shadow-none print:m-0 print:w-full print:p-0" dir={lang === 'ar' ? 'rtl' : 'ltr'}>
            
            {/* ترويسة التقرير */}
            <div className="border-b-2 border-black pb-4 mb-8 flex justify-between items-start">
              <div>
                <h2 className="text-xl font-bold mb-1">{reportTexts.header}</h2>
                <h3 className="text-lg">{reportTexts.ministry}</h3>
                <p className="text-sm text-gray-600">{reportTexts.sector}</p>
              </div>
              <div className={`text-${lang === 'ar' ? 'left' : 'right'}`}>
                <h1 className="text-2xl font-bold text-blue-800 mb-1 uppercase">
                    {reportTexts.title}
                </h1>
                <p className="text-sm text-gray-600">Ref: #{refNumber}</p>
                <p className="text-sm text-gray-600">{today}</p>
              </div>
            </div>

            {/* المحتوى */}
            <div className="mb-8">
              <h4 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4">
                {reportTexts.subjectTitle} <span className="font-normal text-base">{reportTexts.title}</span>
              </h4>
              <p className="text-justify leading-relaxed mb-6 text-sm">
                {reportTexts.subjectBody}
              </p>

              {/* الجدول */}
              <table className="w-full border-collapse border border-black text-center text-sm mb-6">
                <thead className="bg-gray-200 font-bold">
                  <tr>
                    <th className="border border-black p-2 w-10">#</th>
                    <th className={`border border-black p-2 ${lang === 'ar' ? 'text-right' : 'text-left'}`}>{t.table.name}</th>
                    <th className="border border-black p-2">{t.table.category}</th>
                    <th className="border border-black p-2">{t.table.stock}</th>
                    <th className="border border-black p-2">{t.table.status}</th>
                  </tr>
                </thead>
                <tbody>
                  {reportData.length > 0 ? (
                    reportData.map((item, index) => (
                      <tr key={item.id}>
                        <td className="border border-black p-2">{index + 1}</td>
                        <td className={`border border-black p-2 font-bold ${lang === 'ar' ? 'text-right' : 'text-left'}`}>{item.name}</td>
                        <td className="border border-black p-2">{item.category}</td>
                        <td className={`border border-black p-2 font-bold ${Number(item.stock) < 50 ? 'text-red-600' : ''}`}>
                          {item.stock}
                        </td>
                        <td className="border border-black p-2 text-xs">
                           {Number(item.stock) === 0 ? t.status.out : Number(item.stock) < 50 ? t.status.low : t.status.good}
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan="5" className="border border-black p-4 text-gray-500">{t.noData}</td>
                    </tr>
                  )}
                </tbody>
              </table>

              {/* التوصيات */}
              <div className="bg-gray-50 p-4 border border-gray-200 rounded text-sm print:bg-white print:border-black">
                <strong>💡 {reportTexts.recTitle}</strong>
                <ul className={`list-disc mt-2 space-y-1 ${lang === 'ar' ? 'mr-5' : 'ml-5'}`}>
                  {reportType === 'shortage' || reportData.some(i => Number(i.stock) < 50) ? (
                    <>
                      <li className="text-red-600 font-bold">{reportTexts.recDanger}</li>
                      <li>{lang === 'ar' ? 'يرجى توجيه أوامر توريد فورية.' : 'Immediate supply orders recommended.'}</li>
                    </>
                  ) : (
                    <li className="text-green-600">{reportTexts.recSafe}</li>
                  )}
                  <li className="text-gray-500 italic">{reportTexts.footerNote}</li>
                </ul>
              </div>
            </div>

            {/* التوقيعات */}
            <div className="flex justify-between mt-24 pt-8 break-inside-avoid">
              <div className="text-center">
                <p className="font-bold mb-6">{reportTexts.signStore}</p>
                <p className="text-gray-400">....................</p>
              </div>
              <div className="text-center">
                <p className="font-bold mb-6">{reportTexts.signManager}</p>
                <p className="text-gray-400">....................</p>
              </div>
              
              {/* الختم */}
              <div className={`absolute bottom-20 ${lang === 'ar' ? 'left-20' : 'right-20'} opacity-20 -rotate-12 border-4 border-blue-800 text-blue-800 p-4 rounded-full font-bold text-xl print:opacity-50`}>
                TIRYAQ SYSTEM
                <br />
                OFFICIAL DOC
              </div>
            </div>

          </div>
        </div>
      </div>

    </div>
  );
};

export default Reports;